[package]
name = "trampoline"
version = "0.1.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/Justfr33z/trampoline/"
license = "MIT"

[dependencies]
windows = "0.18.0"

[build-dependencies]
windows = "0.18.0"
